### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 23: illegal multibyte sequence

### ISSUE THREAD

**Issue by lindychan** [hanwenlu2016/web-ui#17]
![image](https://user-images.githubusercontent.com/4707768/174424020-c16d12db-9445-4d6a-9536-39abc34996b7.png)

安装之后，执行run.py 报错
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 23: illegal multibyte sequence

`run.py
2022-06-18 13:17:53.411 | INFO     | __main__:<module>:29 - 
══════════════════════════════════════════
║            WEB-UI-AUTO                 ║
║       No one can put out the stars !   ║
══════════════════════════════════════════

2022-06-18 13:17:53.423 | INFO     | public.common:run_del_report:218 - 清除测试报告中.....
Traceback (most recent call last):
  File "D:\lin_space\test\hanwenlu2016web-ui\run.py", line 225, in <module>
    RunPytest.run_bebug()
  File "D:\lin_space\test\hanwenlu2016web-ui\run.py", line 209, in run_bebug
    pytest.main(
  File "D:\conda1\envs\uiautotest\lib\site-packages\_pytest\config\__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "D:\conda1\envs\uiautotest\lib\site-packages\_pytest\config\__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "D:\conda1\envs\uiautotest\lib\site-packages\_pytest\helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "D:\conda1\envs\uiautotest\lib\site-packages\_pytest\config\__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "D:\conda1\envs\uiautotest\lib\site-packages\_pytest\config\__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "D:\conda1\envs\uiautotest\lib\site-packages\_pytest\config\__init__.py", line 1172, in _preparse
    self._initini(args)
  File "D:\conda1\envs\uiautotest\lib\site-packages\_pytest\config\__init__.py", line 1091, in _initini
    rootpath, inipath, inicfg = determine_setup(
  File "D:\conda1\envs\uiautotest\lib\site-packages\_pytest\config\findpaths.py", line 186, in determine_setup
    rootdir, inipath, inicfg = locate_config([ancestor])
  File "D:\conda1\envs\uiautotest\lib\site-packages\_pytest\config\findpaths.py", line 108, in locate_config
    ini_config = load_config_dict_from_file(p)
  File "D:\conda1\envs\uiautotest\lib\site-packages\_pytest\config\findpaths.py", line 45, in load_config_dict_from_file
    iniconfig = _parse_ini_config(filepath)
  File "D:\conda1\envs\uiautotest\lib\site-packages\_pytest\config\findpaths.py", line 30, in _parse_ini_config
    return iniconfig.IniConfig(str(path))
  File "D:\conda1\envs\uiautotest\lib\site-packages\iniconfig\__init__.py", line 54, in __init__
    tokens = self._parse(iter(f))
  File "D:\conda1\envs\uiautotest\lib\site-packages\iniconfig\__init__.py", line 82, in _parse
    for lineno, line in enumerate(line_iter):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 23: illegal multibyte sequence

Process finished with exit code 1
`

**Comment by hanwenlu2016** [comment]
> ![图片](https://user-images.githubusercontent.com/4707768/174424020-c16d12db-9445-4d6a-9536-39abc34996b7.png)
> 
> 安装之后，执行run.py报错 UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 23: invalid multibyte sequence
> 
> `run.py 2022-06-18 13:17:53.411 | 信息 | **主要**::29 - ════════════════════════════════════════WEB- UI-AUTO ║ ║ 没有人能熄灭星星！║══════════════════════════════════════════ _
> 
> 2022-06-18 13:17:53.423 | INFO | public.common:run_del_report:218 - 清除测试报告中..... Traceback (most recent call last): File "D:\lin_space\test\hanwenlu2016web-ui\run.py", line 225, in RunPytest.run_bebug() File "D:\lin_space\test\hanwenlu2016web-ui\run.py", line 209, in run_bebug pytest.main( File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 145, in main config = _prepareconfig(args, plugins) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 324, in _prepareconfig config = pluginmanager.hook.pytest_cmdline_parse( File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy_hooks.py", line 265, in **call** return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult) File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy_manager.py", line 80, in _hookexec return self._inner_hookexec(hook_name, methods, kwargs, firstresult) File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy_callers.py", line 55, in _multicall gen.send(outcome) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\helpconfig.py", line 102, in pytest_cmdline_parse config: Config = outcome.get_result() File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy_result.py", line 60, in get_result raise ex[1].with_traceback(ex[2]) File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy_callers.py", line 39, in _multicall res = hook_impl.function(*args) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 1016, in pytest_cmdline_parse self.parse(args) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 1304, in parse self._preparse(args, addopts=addopts) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 1172, in _preparse self._initini(args) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 1091, in _initini rootpath, inipath, inicfg = determine_setup( File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config\findpaths.py", line 186, in determine_setup rootdir, inipath, inicfg = locate_config([ancestor]) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config\findpaths.py", line 108, in locate_config ini_config = load_config_dict_from_file(p) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config\findpaths.py", line 45, in load_config_dict_from_file iniconfig = _parse_ini_config(filepath) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config\findpaths.py", line 30, in _parse_ini_config return iniconfig.IniConfig(str(path)) File "D:\conda1\envs\uiautotest\lib\site-packages\iniconfig__init__.py", line 54, in **init** tokens = self._parse(iter(f)) File "D:\conda1\envs\uiautotest\lib\site-packages\iniconfig__init__.py", line 82, in _parse for lineno, line in enumerate(line_iter): UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 23: illegal multibyte sequence
> 
> Process finished with exit code 1 `

检查下pytest.ini 文件是不是utf-8

**Comment by daibiao666** [comment]
> ![image](https://user-images.githubusercontent.com/4707768/174424020-c16d12db-9445-4d6a-9536-39abc34996b7.png)
> 
> 安装之后，执行run.py 报错 UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 23: illegal multibyte sequence
> 
> `run.py 2022-06-18 13:17:53.411 | INFO | **main**::29 - ══════════════════════════════════════════ ║ WEB-UI-AUTO ║ ║ No one can put out the stars ! ║ ══════════════════════════════════════════
> 
> 2022-06-18 13:17:53.423 | INFO | public.common:run_del_report:218 - 清除测试报告中..... Traceback (most recent call last): File "D:\lin_space\test\hanwenlu2016web-ui\run.py", line 225, in RunPytest.run_bebug() File "D:\lin_space\test\hanwenlu2016web-ui\run.py", line 209, in run_bebug pytest.main( File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 145, in main config = _prepareconfig(args, plugins) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 324, in _prepareconfig config = pluginmanager.hook.pytest_cmdline_parse( File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy_hooks.py", line 265, in **call** return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult) File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy_manager.py", line 80, in _hookexec return self._inner_hookexec(hook_name, methods, kwargs, firstresult) File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy_callers.py", line 55, in _multicall gen.send(outcome) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\helpconfig.py", line 102, in pytest_cmdline_parse config: Config = outcome.get_result() File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy_result.py", line 60, in get_result raise ex[1].with_traceback(ex[2]) File "D:\conda1\envs\uiautotest\lib\site-packages\pluggy_callers.py", line 39, in _multicall res = hook_impl.function(*args) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 1016, in pytest_cmdline_parse self.parse(args) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 1304, in parse self._preparse(args, addopts=addopts) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 1172, in _preparse self._initini(args) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config__init__.py", line 1091, in _initini rootpath, inipath, inicfg = determine_setup( File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config\findpaths.py", line 186, in determine_setup rootdir, inipath, inicfg = locate_config([ancestor]) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config\findpaths.py", line 108, in locate_config ini_config = load_config_dict_from_file(p) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config\findpaths.py", line 45, in load_config_dict_from_file iniconfig = _parse_ini_config(filepath) File "D:\conda1\envs\uiautotest\lib\site-packages_pytest\config\findpaths.py", line 30, in _parse_ini_config return iniconfig.IniConfig(str(path)) File "D:\conda1\envs\uiautotest\lib\site-packages\iniconfig__init__.py", line 54, in **init** tokens = self._parse(iter(f)) File "D:\conda1\envs\uiautotest\lib\site-packages\iniconfig__init__.py", line 82, in _parse for lineno, line in enumerate(line_iter): UnicodeDecodeError: 'gbk' codec can't decode byte 0xa1 in position 23: illegal multibyte sequence
> 
> Process finished with exit code 1 `

删除pytest.ini 里面的中文注释
